name: ex10_starter
channels:
  - conda-forge
  - defaults
dependencies:
  # Pin to a supported Python version (3.9–3.11). 3.13 is too new for MLflow 3.2.0 and wandb 0.21.
  - python=3.10

  # Core scientific stack
  - pandas=2.3.2
  - scikit-learn=1.7.2
  - matplotlib=3.10.6
  - plotly=6.3.0
  - pillow=11.3.0

  # MLflow & config libraries
  - mlflow=3.2.0
  - hydra-core=1.3.2
  - omegaconf=2.3.0

  # Essentials
  - pip>=24
  - pyyaml

  - pip:
      - wandb==0.21.3
